version: "3"
networks:
  expense:
volumes:
  mysql: # docker volume create mysql
services:
  mysql:
    image: srinikysj4512/mysql:v1
    container_name: mysql 
    volumes:
    - mysql:/var/lib/mysql
  backend:
    image: srinikysj4512/backend:v1
    container_name: backend
    command: sh -c "sleep 5 && node /opt/server/index.js"
    depends_on:
      - mysql
  frontend:
    image: srinikysj4512/frontend:v1
    container_name: frontend
    ports:
    - 80:80
    depends_on:
      - backend